### ISSUE TITLE
No Longer Compatible

### ISSUE THREAD

**Issue by Azathii** [PhillZitt/BetterBombs#11]
As of Stardew Valley 1.6.4, SMAPI 4.0.8, this mod is no longer compatible.

[SMAPI]    Skipped mods
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods could not be added to your game.
[SMAPI]       - BetterBombs 1.1.0 because it's no longer compatible. Please check for a new version at https://smapi.io/mods

Any update to this mod would be greatly appreciated. Thanks.

**Comment by justastranger** [comment]
Mod was updated to 1.1.2 yesterday
