### ISSUE TITLE
Change Ignore List to Allow List or Enhance Ignore list

### ISSUE THREAD

**Issue by PhillZitt** [PhillZitt/BetterBombs#5]
Originally I didn't have a great understanding of how the objects worked, so I thought an ignore list would be sufficient to keep out the bad items. Turns out this was probably wrong.

I should instead use an allowlist that has everything that I want to be picked up. This means that I'll have to keep an eye for any future items, and also that mods that add new items won't be automatically supported. I'd rather do the ignorelist to ensure compatibility, so look into that more.

**Comment by Traehgniw** [comment]
Is this why a bomb that went off by an artifact spot dropped it as an item?

**Comment by PhillZitt** [comment]
Yes. If you get an item that shouldn't be an item - weeds, stone, most things with a description of "..." - this is the cause.

**Comment by PhillZitt** [comment]
Worked on this further in e4dc25ec9cff1af1d7fbdba32ecd06178de956a4 , this should prevent most (if not all) unintended item pickups, but it is much more restrictive as to what is considered 'pickable'.

**Comment by PhillZitt** [comment]
I've played with this for a few days and I haven't noticed any abnormal pickups. I'm marking this completed.
