### ISSUE TITLE
Bomb explosion is centered at the center of the screen, not where the bomb is placed

### ISSUE THREAD

**Issue by echobunny** [PhillZitt/BetterBombs#6]
Issue: bomb placed at farmer explodes at center of screen. leaving mine items near farmer untouched
Settings:
{
  "BreakClumps": true,
  "CollectMinerals": true,
  "DamageFarmers": false,
  "Radius": 25.0,
  "Damage": 25.0
}

Reproducible: Yes

![StardewModdingAPI 2021-01-25 18-13-32-181](https://user-images.githubusercontent.com/32854028/105777888-33b1d880-5f39-11eb-82d8-b280b8fe58be.jpg)
![StardewModdingAPI 2021-01-25 18-13-45-267](https://user-images.githubusercontent.com/32854028/105777891-357b9c00-5f39-11eb-8097-d0e86439fd9e.jpg)

SMAPI Log: https://smapi.io/log/862c14a589764484ad01628730039024

**Comment by PhillZitt** [comment]
Thank you for the excellent bug report.

I've noticed this in my game as well, and have been looking into it. I think it's a bug with the base explode code, when the radius is too large. I'm still looking into it, but it is far more noticeable with Radius > 3.0.

**Comment by echobunny** [comment]
Turning the radius down to 3 helped (but what fun is that?) and the explosion is centered again.

**Comment by PhillZitt** [comment]
I looked deeper into this, and this is due to how the base game is calculating the maximum size of an explosion (or something like that. I only lightly follow the base code here.) I'll add a note on the mod page to be careful with values above 3, but it's not something under the purview of this mod.
